name: the_chess_engine
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chess: ^0.7.0
  flutter_svg: ^1.1.3
  provider: ^6.0.3
  localstorage: ^3.0.6
  flutter_localizations:
    sdk: flutter
  graphview: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: AnonymousPro
      fonts:
        - asset: fonts/AnonymousPro.ttf